// ====================================================================
// SHARED PRODUCT DATA — Single source of truth for all products
// Used by: product.html, quiz.html, shop.html (through product-pages.js)
// ====================================================================
// To add a new plant, add an object to this array with the same shape.
// Image paths are relative to the pages/ directory (add ../ for root level).

var ALL_PRODUCTS = [
    { name: 'Snake Plant', price: 22, category: 'Indoor Plant', scientificName: 'Sansevieria trifasciata', image: '../assets/white_background_202607131940.jpeg', tags: 'air-purifying,low-light', badge: 'Bestseller', stock: 'in-stock', water: 'Every 2-3 weeks — drought tolerant', light: 'Low to bright indirect', temp: '15–30°C', petSafe: 'Toxic if ingested', fertilizer: 'Every 3 months', winterCare: 'Keep above 10°C; water every 4-6 weeks', survivalTime: 'Up to 4 weeks without water', description: 'The Snake Plant features tall, upright sword-shaped leaves with striking green and yellow variegated patterns that add architectural drama to any room. Famous for converting CO2 into oxygen at night, it is an ideal bedroom companion. This drought-tolerant beauty thrives on neglect and can survive low-light corners where most other plants struggle. One of the hardiest houseplants you can own, it is the ultimate low-maintenance air-purifying choice for modern homes, offices, and beginners who want greenery without the guilt.' },
    { name: 'Jade Plant', price: 25, category: 'Succulent', scientificName: 'Crassula ovata', image: '../assets/Jade_Plant_white_background_202607131940.jpeg', tags: 'succulent', badge: 'Popular', stock: 'in-stock', water: 'Every 2-3 weeks', light: 'Bright indirect to direct', temp: '18–30°C', petSafe: 'Toxic to pets', fertilizer: 'Every 3 months', winterCare: 'Keep above 5°C; water only when soil is bone dry', survivalTime: '3-4 weeks without water', description: 'The Jade Plant is a beloved succulent symbolizing good luck and prosperity, often called the Money Tree. Its thick, fleshy oval leaves grow on sturdy woody stems, developing a beautiful bonsai-like tree structure over time. Native to South Africa, it produces delicate star-shaped white or pink flowers in winter when given enough sunlight. Incredibly forgiving, it simply needs water when the soil dries completely and bright light. With proper care, a Jade Plant can live for decades, becoming a cherished living heirloom passed through generations.' },
    { name: 'Haworthia', price: 20, category: 'Succulent', scientificName: 'Haworthia fasciata', image: '../assets/Haworthia_white_background_202607131940.jpeg', tags: 'succulent,small', badge: 'Trending', stock: 'in-stock', water: 'Every 3 weeks', light: 'Bright indirect', temp: '18–27°C', petSafe: 'Non-toxic', fertilizer: 'Yearly', winterCare: 'Keep above 5°C; reduce watering to once a month', survivalTime: '4-6 weeks without water', description: 'Haworthia is a charming miniature succulent perfect for desks, shelves, and tiny spaces. Its distinctive rosette of pointed, fleshy leaves is covered in white pearly bumps and translucent stripes, giving it a striking zebra-like appearance. Unlike many succulents, it thrives in moderate indirect light rather than direct sun, making it one of the few succulents that genuinely does well indoors. Its slow growth means it stays compact for years, requiring minimal repotting and care.' },
    { name: 'Spider Plant', price: 20, category: 'Indoor Plant', scientificName: 'Chlorophytum comosum', image: '../assets/Spider_Plant_white_background_202607131940.jpeg', tags: 'air-purifying,low-light', badge: 'Popular', stock: 'in-stock', water: 'Moderate — keep soil slightly moist', light: 'Bright indirect', temp: '18–32°C', petSafe: 'Non-toxic, pet-friendly!', fertilizer: 'Monthly in summer', winterCare: 'Keep above 10°C; mist occasionally in dry indoor air', survivalTime: '2 weeks without water', description: 'The Spider Plant is a classic favorite with cascading arching leaves and adorable baby spiderettes that dangle from long stems. Its vibrant green and white striped foliage creates a stunning waterfall effect perfect for hanging baskets and high shelves. Completely non-toxic to cats and dogs, it is one of the most pet-friendly houseplants available. Spider plants are champion air-purifiers that remove formaldehyde and xylene from indoor air.' },
    { name: 'Syngonium', price: 18, category: 'Indoor Plant', scientificName: 'Syngonium podophyllum', image: '../assets/Syngonium_white_background_202607131940.jpeg', tags: 'trailing,low-light', badge: 'Trending', stock: 'in-stock', water: 'When soil feels dry', light: 'Low to bright indirect', temp: '17–30°C', petSafe: 'Toxic if ingested', fertilizer: 'Monthly', winterCare: 'Keep above 15°C; avoid cold drafts', survivalTime: '1-2 weeks without water', description: 'Syngonium, also known as the Arrowhead Vine, is a fast-growing tropical beauty admired for its uniquely shaped leaves that transform as the plant matures — from arrow-shaped juvenile leaves to multi-lobed adult foliage. Its trailing climbing growth habit makes it incredibly versatile; train it up a moss pole for a vertical statement or let it cascade from a hanging basket.' },
    { name: 'ZZ Plant', price: 35, category: 'Indoor Plant', scientificName: 'Zamioculcas zamiifolia', image: '../assets/ZZ_Plant_white_background_202607131940.jpeg', tags: 'low-light', badge: 'Bestseller', stock: 'in-stock', water: 'Every 2-3 weeks — drought tolerant', light: 'Low to bright indirect', temp: '18–30°C', petSafe: 'Toxic if ingested', fertilizer: 'Every 3 months', winterCare: 'Keep above 10°C; water every 4-6 weeks', survivalTime: 'Up to 5 weeks without water', description: 'The ZZ Plant is virtually indestructible, earning its reputation as the houseplant that refuses to die. Its glossy, dark green waxy leaves emerge from thick potato-like rhizomes that store water, allowing it to survive months of drought. This architectural beauty handles low light, fluorescent light, and complete neglect with equal grace.' },
    { name: 'Peace Lily', price: 28, category: 'Indoor Plant', scientificName: 'Spathiphyllum wallisii', image: '../assets/Peace_Lily_white_background_202607131940.jpeg', tags: 'air-purifying,flowering', badge: 'Premium', stock: 'in-stock', water: 'Weekly — keep moist', light: 'Low to medium indirect', temp: '18–27°C', petSafe: 'Toxic to pets', fertilizer: 'Every 6 weeks', winterCare: 'Keep above 15°C; reduce watering; mist leaves', survivalTime: '7-10 days without water', description: 'The Peace Lily is an elegant flowering houseplant renowned for its graceful white spathes that bloom repeatedly throughout the year. Its lush, dark green foliage creates a tropical feel while pure white flowers add serenity to any room. According to NASA studies, it is one of the best air-purifying plants, effectively removing benzene and formaldehyde from indoor air.' },
    { name: 'Kalanchoe', price: 22, category: 'Succulent', scientificName: 'Kalanchoe blossfeldiana', image: '../assets/Kalanchoe_white_background_202607131940.jpeg', tags: 'succulent,flowering', badge: 'Popular', stock: 'in-stock', water: 'Every 2 weeks', light: 'Bright direct to indirect', temp: '18–32°C', petSafe: 'Toxic to pets', fertilizer: 'Monthly', winterCare: 'Keep above 7°C; water every 3-4 weeks', survivalTime: '3 weeks without water', description: 'Kalanchoe is a cheerful flowering succulent that rewards owners with months of vibrant blooms in shades of red, pink, orange, yellow, or white. Its thick, fleshy dark green leaves with scalloped edges form a compact rosette, creating a beautiful backdrop for clusters of tiny star-shaped flowers.' },
    { name: 'Adenium', price: 35, category: 'Succulent', scientificName: 'Adenium obesum', image: '../assets/Adenium_white_background_202607131940.jpeg', tags: 'succulent,flowering', badge: 'Premium', stock: 'in-stock', water: 'Weekly in summer', light: 'Full sun', temp: '20–35°C', petSafe: 'Toxic if ingested', fertilizer: 'Monthly', winterCare: 'Keep above 10°C; nearly dry during winter dormancy', survivalTime: '4-6 weeks without water', description: 'The Desert Rose is a stunning succulent shrub with dramatic architectural impact. Its thick, swollen caudex base resembles an ancient bonsai trunk, while clusters of trumpet-shaped flowers in brilliant pink, red, or white create a spectacular tropical display. Native to arid regions of Africa and Arabia, this sun-worshipper thrives in hot, bright conditions.' },
    { name: 'Portulaca', price: 15, category: 'Succulent', scientificName: 'Portulaca grandiflora', image: '../assets/Portulaca_white_background_202607131940.jpeg', tags: 'succulent,flowering', badge: 'Bestseller', stock: 'in-stock', water: 'Every 2-3 days', light: 'Full sun', temp: '20–35°C', petSafe: 'Non-toxic', fertilizer: 'Monthly', winterCare: 'Annual — dies in frost; collect seeds for replanting', survivalTime: '5-7 days without water in summer', description: 'Portulaca, also known as Moss Rose, is a vibrant flowering succulent that brings a carpet of color to sunny spaces. Its succulent needle-like leaves store water efficiently, making it exceptionally drought-tolerant and perfect for hot Indian summers. The colorful cup-shaped flowers in neon shades of pink, orange, yellow, and red open in the morning sun and close at night.' }
];
